import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, Boxes, Check, CircleDashed, ClipboardList, ExternalLink, Fingerprint, LockKeyhole, RotateCcw, ShieldCheck, TicketCheck, TriangleAlert, UserRound } from 'lucide-react'
import { Link, useRoute } from 'wouter'
import { visionQcApi } from '../api/visionQc'
import { ErrorState, LoadingState } from '../components/Feedback'
import { StatusBadge } from '../components/StatusBadge'
import { Timeline } from '../components/Timeline'
import { useI18n } from '../hooks/useI18n'
import { decisionLabel, statusLabel } from '../i18n'
import type { QualityIncident } from '../types'
import { formatAuditActor, formatAuditDetail, formatDateTime, formatStation } from '../utils'

const actionLabel = (language: 'zh' | 'en', action: string) => ({ HOLD_BATCH: language === 'zh' ? '暂扣批次' : 'Hold batch', CREATE_TICKET: language === 'zh' ? '创建质量工单' : 'Create quality ticket', WAIT_FOR_VERIFICATION: language === 'zh' ? '等待验证' : 'Await verification' } as Record<string, string>)[action] ?? action

export function IncidentPage() {
  const [, params] = useRoute('/incidents/:id'); const id = params?.id ?? ''; const { t, language } = useI18n(); const [incident, setIncident] = useState<QualityIncident | null>(null); const [error, setError] = useState<unknown>(null)
  const load = useCallback(async () => { try { setError(null); setIncident(await visionQcApi.getIncident(id)) } catch (caught) { setError(caught) } }, [id]); useEffect(() => { void load() }, [load]); useEffect(() => { if (!incident || !['ACTION_PENDING', 'ACTION_EXECUTING'].includes(incident.status)) return; const timer = window.setTimeout(() => void load(), 900); return () => window.clearTimeout(timer) }, [incident, load])
  if (error) return <div className="page"><ErrorState error={error} onRetry={load} /></div>
  if (!incident) return <div className="page"><LoadingState label={language === 'zh' ? '正在重建质量事件时间线…' : 'Reconstructing quality-event timeline…'} /></div>
  const isClosed = incident.status === 'CLOSED'; const hasOutcome = Boolean(incident.outcome); const hasVerification = Boolean(incident.verificationRecord)
  return <div className="page incident-page"><div className="breadcrumb"><Link href="/reviews"><ArrowLeft size={14} />{t('nav.reviews')}</Link><span>/</span><strong>{incident.id}</strong></div><div className="detail-heading incident-heading"><div><span className="page-kicker">{t('incidents.kicker')}</span><div className="title-line"><h1>{t('incident.title', { id: incident.id })}</h1><StatusBadge status={incident.status} label={statusLabel(language, incident.status)} /></div><p>{t('incident.derived')}</p></div><Link className="secondary-button" href={`/inspections/${incident.inspectionId}`}>{t('incident.viewEvidence')}<ExternalLink size={15} /></Link></div>
    <div className="incident-summary-grid"><section className="incident-hero panel"><div className="incident-band"><span>{language === 'zh' ? '处置' : 'Disposition'}</span><strong>{decisionLabel(language, incident.disposition)}</strong><i /><span>{language === 'zh' ? '严重度' : 'Severity'}</span><strong>{incident.severity === 'MAJOR' ? (language === 'zh' ? '主要' : 'Major') : (language === 'zh' ? '关键' : 'Critical')}</strong></div><div className="incident-title"><div className="incident-icon"><TriangleAlert size={27} /></div><div><span>{language === 'zh' ? '人工确认不合格' : 'Human-confirmed nonconformance'}</span><h2>{incident.productCode} · {incident.batchNo}</h2><p>{language === 'zh' ? '模型异常分数保留为证据，不作为根因事实。' : 'The anomaly score is retained as evidence, not as a root-cause fact.'}</p></div></div><dl className="incident-facts"><div><dt><UserRound size={15} />{t('incident.owner')}</dt><dd>{incident.owner}</dd></div><div><dt><Boxes size={15} />{language === 'zh' ? '工位' : 'Station'}</dt><dd>{formatStation(incident.station, language)}</dd></div><div><dt><Fingerprint size={15} />{language === 'zh' ? '检测记录' : 'Inspection'}</dt><dd><Link href={`/inspections/${incident.inspectionId}`}>{incident.inspectionId}</Link></dd></div><div><dt><ClipboardList size={15} />{language === 'zh' ? '创建时间' : 'Created'}</dt><dd>{formatDateTime(incident.createdAt, true, language)}</dd></div></dl></section>
      <section className="panel closure-gate"><div className="section-title"><div><span className="eyebrow">{t('incident.closure')}</span><h2>{t('incident.closure')}</h2></div><LockKeyhole size={19} /></div><ul><li className="done"><Check size={15} /><span><strong>{t('incident.namedDecision')}</strong><small>{formatAuditActor(incident.evidence.decisionActor, language)} · {decisionLabel(language, incident.disposition)}</small></span></li><li className="done"><Check size={15} /><span><strong>{t('incident.owner')}</strong><small>{incident.owner}</small></span></li><li className={hasOutcome ? 'done' : undefined}>{hasOutcome ? <Check size={15} /> : <CircleDashed size={15} />}<span><strong>{t('incident.outcome')}</strong><small>{incident.outcome ?? (language === 'zh' ? '等待 QMS 更新' : 'Waiting for QMS update')}</small></span></li><li className={hasVerification ? 'done' : undefined}>{hasVerification ? <Check size={15} /> : <CircleDashed size={15} />}<span><strong>{t('incident.verification')}</strong><small>{incident.verificationRecord ?? (language === 'zh' ? '尚未提交' : 'Not submitted')}</small></span></li></ul><button disabled className="secondary-button full-button">{isClosed ? <Check size={15} /> : <LockKeyhole size={15} />}{isClosed ? t('incident.closeReady') : t('incident.closeBlocked')}</button></section></div>

    <section className="panel decision-evidence-card"><div className="section-title"><div><span className="eyebrow">{t('incident.evidence')}</span><h2>{t('incident.evidence')}</h2></div><ShieldCheck size={20} /></div><blockquote>“{language === 'zh' ? formatAuditDetail(incident.evidence.decisionReason) : 'The reviewer observed a visible anomaly and kept the batch controlled for investigation.'}”</blockquote><div className="decision-evidence-grid"><span><small>{language === 'zh' ? '操作者' : 'Actor'}</small><strong>{formatAuditActor(incident.evidence.decisionActor, language)}</strong></span><span><small>{t('inspection.score')}</small><strong>{incident.evidence.score.toFixed(2)}</strong></span><span><small>Model</small><strong>{incident.evidence.modelVersion}</strong></span><span><small>Policy</small><strong>{incident.evidence.policyVersion}</strong></span></div></section>
    <section className="panel connector-section"><div className="section-title"><div><span className="eyebrow">{t('incident.operations')}</span><h2>{t('incident.operations')}</h2></div><small><i />{t('incident.simulated')}</small></div><div className="connector-grid">{incident.externalActions.map((action) => <article key={action.id}><div className="connector-head"><div className={action.system === 'Mock MES' ? 'mes' : 'qms'}>{action.system === 'Mock MES' ? <Boxes size={19} /> : <TicketCheck size={19} />}</div><span><strong>{language === 'zh' ? action.system.replace('Mock', '模拟') : action.system}</strong><small>{actionLabel(language, action.action)}</small></span><StatusBadge status={action.status} size="sm" /></div><p>{language === 'zh' ? action.message : 'The simulated connector retained the request and its idempotency key.'}</p><dl><div><dt>{language === 'zh' ? '尝试次数' : 'Attempts'}</dt><dd>{action.attempts}</dd></div><div><dt>{language === 'zh' ? '外部编号' : 'External ref'}</dt><dd>{action.externalRef ?? '—'}</dd></div><div className="wide"><dt>{language === 'zh' ? '防重复编号' : 'Idempotency key'}</dt><dd><code>{action.idempotencyKey}</code></dd></div><div className="wide"><dt>{language === 'zh' ? '最后更新' : 'Updated'}</dt><dd>{formatDateTime(action.updatedAt, true, language)}</dd></div></dl>{action.status === 'FAILED' && <button className="secondary-button"><RotateCcw size={14} />{language === 'zh' ? '授权重放' : 'Authorize replay'}</button>}</article>)}</div><div className="idempotency-note"><ShieldCheck size={17} /><span><strong>{t('incident.idempotency')}</strong> {t('incident.idempotencyBody')}</span></div></section>
    <section className="panel incident-timeline-panel"><div className="section-title"><div><span className="eyebrow">{language === 'zh' ? '完整审计链' : 'Full audit chain'}</span><h2>{t('incident.timeline')}</h2></div><div className="append-only-chip"><LockKeyhole size={13} />{language === 'zh' ? '只追加审计' : 'Append-only audit'}</div></div><Timeline events={incident.timeline} /></section>
  </div>
}
