import { useCallback, useEffect, useState } from 'react'
import { AlertTriangle, ArrowRight, Boxes, Clock3, Cpu, Fingerprint, Gauge, MapPin, ScanLine, ShieldAlert } from 'lucide-react'
import { Link, useRoute } from 'wouter'
import { visionQcApi } from '../api/visionQc'
import { ErrorState, LoadingState } from '../components/Feedback'
import { EvidenceViewer } from '../components/EvidenceViewer'
import { StatusBadge } from '../components/StatusBadge'
import { Timeline } from '../components/Timeline'
import { useI18n } from '../hooks/useI18n'
import type { Inspection } from '../types'
import { formatDateTime, formatPolicyReason, formatScore, formatSource, formatStation } from '../utils'

export function InspectionPage() {
  const [, params] = useRoute('/inspections/:id'); const id = params?.id ?? ''; const { t, language } = useI18n(); const [inspection, setInspection] = useState<Inspection | null>(null); const [error, setError] = useState<unknown>(null)
  const load = useCallback(async () => { try { setError(null); setInspection(await visionQcApi.getInspection(id)) } catch (caught) { setError(caught) } }, [id])
  useEffect(() => { void load() }, [load]); const isTransient = Boolean(inspection && ['RECEIVED', 'VALIDATED', 'INFERENCING', 'SCORED'].includes(inspection.status)); useEffect(() => { if (!isTransient) return; const timer = window.setTimeout(() => void load(), 850); return () => window.clearTimeout(timer) }, [isTransient, load])
  if (error) return <div className="page"><ErrorState error={error} onRetry={load} /></div>
  if (!inspection) return <div className="page"><LoadingState label={language === 'zh' ? '正在读取检测详情…' : 'Loading inspection detail…'} /></div>
  const { inference, policy } = inspection
  const policyTitle = policy?.decision === 'BATCH_HOLD_AND_REVIEW' ? (language === 'zh' ? '批次已暂时停止，等待人工确认' : 'Batch held while waiting for human confirmation') : policy?.decision === 'AUTO_RELEASE' ? (language === 'zh' ? '分数低于复核线，策略允许放行' : 'Below review threshold; policy allows release') : language === 'zh' ? '这张图片需要人工确认' : 'This image needs human confirmation'
  const policyReason = formatPolicyReason(policy?.reason, language)
  return <div className="page inspection-page"><div className="page-heading"><div><span className="page-kicker">{t('inspection.kicker')}</span><div className="title-line"><h1>{t('inspection.title')}</h1><StatusBadge status={inspection.status} /></div><p>{inspection.context.batchNo} · {formatStation(inspection.context.station, language)} · {formatDateTime(inspection.context.capturedAt, true, language)}</p></div>{inspection.reviewTaskId && <Link className="primary-button" href={`/reviews/${inspection.reviewTaskId}`}>{t('inspection.review')}<ArrowRight size={17} /></Link>}</div>
    {isTransient && <div className="processing-ribbon" role="status"><ScanLine className="scan-icon" size={20} /><div><strong>{t('inspection.processing')}</strong><span>{t('inspection.processingBody')}</span></div><code>{inspection.correlationId}</code></div>}
    {inspection.failure && <div className="failure-banner" role="alert"><ShieldAlert size={24} /><div><strong>{inspection.failure.message}</strong><p>{language === 'zh' ? inspection.failure.nextStep : 'Review the evidence and confirm the model and deployment status.'}</p><code>{inspection.failure.code} · {inspection.correlationId}</code></div></div>}
    {inspection.qualityFlags && inspection.qualityFlags.length > 0 && <div className="quality-flag-banner" role="status"><ShieldAlert size={18} /><span><strong>{t('inspection.qualityGate')}{language === 'zh' ? '：' : ': '}</strong>{inspection.qualityFlags.join(language === 'zh' ? '、' : ', ')}. {language === 'zh' ? '系统没有把这张图自动放行，已转人工复核。' : 'The image was not auto-released and was routed to human review.'}</span></div>}
    <div className="inspection-grid"><div className="inspection-main"><EvidenceViewer inspection={inspection} /><section className="panel evidence-metadata"><div className="section-title"><div><span className="eyebrow">{t('inspection.kicker')}</span><h2>{language === 'zh' ? '样本与生产上下文' : 'Sample and production context'}</h2></div><small>{language === 'zh' ? '接收后只读' : 'Read-only after receipt'}</small></div><dl className="metadata-grid"><div><dt><Boxes size={15} />{language === 'zh' ? '产品 / 版本' : 'Product / revision'}</dt><dd>{inspection.context.productCode} · {inspection.context.productRevision}</dd></div><div><dt><Fingerprint size={15} />{language === 'zh' ? '批次号' : 'Batch'}</dt><dd>{inspection.context.batchNo}</dd></div><div><dt><MapPin size={15} />{language === 'zh' ? '工位' : 'Station'}</dt><dd>{formatStation(inspection.context.station, language)}</dd></div><div><dt><Clock3 size={15} />{language === 'zh' ? '采集时间' : 'Captured'}</dt><dd>{formatDateTime(inspection.context.capturedAt, true, language)}</dd></div><div className="wide"><dt><Fingerprint size={15} />SHA-256</dt><dd><code>{inspection.image.sha256}</code></dd></div><div><dt>{language === 'zh' ? '图片来源' : 'Source'}</dt><dd>{formatSource(inspection.context.source, language)}</dd></div>{Object.entries(inspection.context.metadata ?? {}).filter(([key]) => key !== 'quality_flags').slice(0, 6).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{typeof value === 'object' ? JSON.stringify(value) : String(value)}</dd></div>)}</dl></section></div>
      <aside className="inspection-side"><section className="panel score-card"><div className="section-title"><div><span className="eyebrow">{t('inspection.score')}</span><h2>{t('inspection.score')}</h2></div><Gauge size={20} /></div><div className="score-readout"><strong>{formatScore(inference?.score)}</strong><span>/ 1.00</span></div>{inference && policy ? <><div className="threshold-meter" aria-label={`${t('inspection.score')} ${inference.score}, ${t('inspection.reviewThreshold')} ${policy.reviewThreshold}, ${t('inspection.holdThreshold')} ${policy.holdThreshold}`}><div className="meter-zones"><i /><i /><i /></div><span className="meter-marker review" style={{ left: `${policy.reviewThreshold * 100}%` }}><b>{language === 'zh' ? '复核' : 'Review'}</b></span><span className="meter-marker hold" style={{ left: `${policy.holdThreshold * 100}%` }}><b>{language === 'zh' ? '暂扣' : 'Hold'}</b></span><span className="score-marker" style={{ left: `${inference.score * 100}%` }}><b>{inference.score.toFixed(2)}</b></span></div><div className="threshold-labels"><span>{language === 'zh' ? '自动放行区' : 'Auto-release'}</span><span>{language === 'zh' ? '人工复核区' : 'Human review'}</span><span>{language === 'zh' ? '暂扣复核区' : 'Batch hold'}</span></div><div className="policy-result"><AlertTriangle size={18} /><div><strong>{policyTitle}</strong><span>{policyReason}</span></div></div></> : <p className="muted-copy">{language === 'zh' ? '模型未返回有效结果，策略已执行安全降级。' : 'No valid model result; policy used safety degrade.'}</p>}</section>
        <section className="panel model-card"><details className="technical-details"><summary><span><Cpu size={18} /><strong>{t('inspection.technical')}</strong><small>{t('inspection.technicalHint')}</small></span><span>{language === 'zh' ? '展开' : 'Expand'}</span></summary><dl><div><dt>Model</dt><dd>{inference ? `${inference.modelId}@${inference.modelVersion}` : '—'}</dd></div><div><dt>Feature bank</dt><dd>{inference?.featureBankVersion ?? '—'}</dd></div><div><dt>Policy</dt><dd>{policy?.version ?? 'Safety-degrade policy'}</dd></div><div><dt>Latency</dt><dd>{inference ? `${inference.latencyMs} ms` : '—'}</dd></div><div><dt>Runtime</dt><dd>{inference?.device ?? '—'}</dd></div><div><dt>Correlation ID</dt><dd><code>{inspection.correlationId}</code></dd></div></dl></details></section><section className="semantic-boundary"><span>{t('inspection.boundary')}</span><strong>{t('inspection.suspicious')}</strong><p>{t('inspection.suspiciousBody')}</p></section></aside>
    </div><section className="panel timeline-panel"><div className="section-title"><div><span className="eyebrow">{language === 'zh' ? '只追加审计' : 'Append-only audit'}</span><h2>{language === 'zh' ? '审计时间线' : 'Audit timeline'}</h2></div><small>{language === 'zh' ? '普通用户不可修改或删除' : 'Cannot be edited by regular users'}</small></div><Timeline events={inspection.timeline} /></section>
  </div>
}
