import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Camera, Check, CheckCircle2, CircleHelp, CloudUpload, FolderOpen, ImagePlus, LockKeyhole, Palette, PlugZap, ShieldAlert, ShieldCheck, UploadCloud } from 'lucide-react'
import { useLocation } from 'wouter'
import { useI18n } from '../hooks/useI18n'
import { industryPacks, localized, useTenantConfig, type CaptureSource, type IndustryId } from '../config/tenant'

const steps = ['onboarding.step1', 'onboarding.step2', 'onboarding.step3', 'onboarding.step4', 'onboarding.step5', 'onboarding.step6'] as const

export function OnboardingPage() {
  const [, navigate] = useLocation()
  const { t, language } = useI18n()
  const { config, industryPack, setIndustry, updateBranding, updatePrivacy, updateConnectors, updateRisk, updateConfig, resetConfig } = useTenantConfig()
  const [step, setStep] = useState(0)
  const [source, setSource] = useState<CaptureSource>('example')
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [testing, setTesting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const logoInput = useRef<HTMLInputElement>(null)

  useEffect(() => { document.title = `${config.branding.displayName} · ${t('nav.setup')}` }, [config.branding.displayName, t])
  function chooseIndustry(id: IndustryId) { setIndustry(id); setError(null) }
  function chooseSource(next: CaptureSource) { setSource(next); setSelectedFile(null); setError(null) }
  function handleFile(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) setSelectedFile(file) }
  function handleLogo(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = () => { if (typeof reader.result === 'string') updateBranding({ logoUrl: reader.result }) }
    reader.readAsDataURL(file)
  }
  function nextStep() {
    setError(null)
    if (step === 2 && source !== 'example' && !selectedFile) { setError(language === 'zh' ? '请先选择一张示例图片；没有真实相机或文件夹也可以继续。' : 'Choose a sample image first; you can continue without a real camera or folder.'); return }
    setStep((current) => Math.min(current + 1, steps.length - 1))
  }
  async function testConnector() {
    setTesting(true); setError(null)
    await new Promise((resolve) => window.setTimeout(resolve, 420))
    updateConnectors({ lastTestedAt: new Date().toISOString(), testStatus: 'passed', mode: 'mock' })
    setTesting(false)
  }
  function generateWorkspace() { updateConfig({ setupComplete: true }); navigate('/') }

  const sourceButton = (id: CaptureSource, icon: typeof ImagePlus, title: string, body: string) => { const Icon = icon; return <button type="button" className={`source-choice ${source === id ? 'selected' : ''}`} aria-pressed={source === id} onClick={() => chooseSource(id)}><span className="source-choice-icon"><Icon size={19} /></span><span><strong>{title}</strong><small>{body}</small></span>{source === id && <CheckCircle2 size={17} />}</button> }
  const inputLabel = language === 'zh' ? '示例图片文件' : 'Sample image file'
  return <div className="page onboarding-page">
    <div className="page-heading onboarding-heading"><div><span className="page-kicker">{t('onboarding.kicker')}</span><h1>{t('onboarding.title')}</h1><h2 className="path-heading">{language === 'zh' ? '从一张图开始检测' : 'Start with one image'}</h2><p>{t('onboarding.subtitle')}</p></div><div className="onboarding-status"><span>{t('onboarding.progress')}</span><strong>0{step + 1} <small>/ 06</small></strong><div className="progress-track"><i style={{ width: `${((step + 1) / steps.length) * 100}%` }} /></div></div></div>
    <div className="onboarding-shell">
      <aside className="onboarding-sidebar"><div className="sidebar-label">VQ / SETUP</div><ol>{steps.map((key, index) => <li key={key} className={index === step ? 'active' : index < step ? 'complete' : ''}><button type="button" onClick={() => index <= step && setStep(index)} disabled={index > step}><span>{index < step ? <Check size={14} /> : String(index + 1).padStart(2, '0')}</span><strong>{t(key)}</strong></button></li>)}</ol><div className="sidebar-boundary"><ShieldCheck size={16} /><span><strong>{t('onboarding.hardRule')}</strong>{t('onboarding.alwaysOn')}</span></div></aside>
      <section className="onboarding-card">
        {step === 0 && <div className="wizard-step"><div className="wizard-title"><span className="step-number">01</span><div><h2>{t('onboarding.chooseIndustry')}</h2><p>{t('onboarding.chooseIndustryBody')}</p></div></div><div className="industry-grid">{(Object.values(industryPacks)).map((pack) => <button type="button" key={pack.id} className={`industry-card ${config.industry === pack.id ? 'selected' : ''}`} onClick={() => chooseIndustry(pack.id)}><span className="industry-swatch" style={{ background: pack.colors.primary }} /><span className="industry-card-copy"><strong>{localized(pack.name, language)}</strong><small>{localized(pack.description, language)}</small></span><span className="industry-check">{config.industry === pack.id ? <CheckCircle2 size={18} /> : <CircleHelp size={17} />}</span>{pack.id === 'automotive-paint' && <><span className="industry-tag">{language === 'zh' ? '示例包' : 'Example pack'}</span><p className="onboarding-disclaimer">{t('onboarding.disclaimerEn')}</p></>}</button>)}</div><div className="quick-source"><div><span className="eyebrow">{t('onboarding.captureTitle')}</span><p>{t('onboarding.captureBody')}</p></div><div className="source-choice-grid">{sourceButton('example', ImagePlus, t('onboarding.example'), t('onboarding.exampleBody'))}{sourceButton('folder', FolderOpen, t('onboarding.folder'), t('onboarding.folderBody'))}{sourceButton('camera', Camera, t('onboarding.camera'), t('onboarding.cameraBody'))}</div>{source !== 'example' && <p className="privacy-callout"><LockKeyhole size={15} /><span><strong>{t('onboarding.local')}</strong> · {t('gateway.privacyBody')} · {t('onboarding.consentHint')}</span></p>}</div></div>}

        {step === 1 && <div className="wizard-step"><div className="wizard-title"><span className="step-number">02</span><div><h2>{t('onboarding.brandTitle')}</h2><p>{t('onboarding.brandBody')}</p></div></div><div className="brand-form-grid"><label><span>{t('onboarding.displayName')}</span><input value={config.branding.displayName} onChange={(event) => updateBranding({ displayName: event.target.value })} /></label><label><span>{t('onboarding.siteName')}</span><input value={config.branding.siteName} onChange={(event) => updateBranding({ siteName: event.target.value })} /></label><label className="full"><span>{t('onboarding.logoUrl')} <em>{t('common.optional')}</em></span><div className="input-with-action"><input value={config.branding.logoUrl?.startsWith('data:') ? '' : config.branding.logoUrl ?? ''} placeholder={t('onboarding.logoPlaceholder')} onChange={(event) => updateBranding({ logoUrl: event.target.value || null })} /><button type="button" className="secondary-button" onClick={() => logoInput.current?.click()}><CloudUpload size={15} />{t('onboarding.logoUpload')}</button><input ref={logoInput} className="visually-hidden" type="file" accept="image/*" onChange={handleLogo} /></div><small>{t('onboarding.logoHint')}</small></label><label><span>{t('onboarding.primary')}</span><div className="color-input"><input type="color" value={config.branding.primaryColor} onChange={(event) => updateBranding({ primaryColor: event.target.value })} /><code>{config.branding.primaryColor}</code></div></label><label><span>{t('onboarding.accent')}</span><div className="color-input"><input type="color" value={config.branding.accentColor} onChange={(event) => updateBranding({ accentColor: event.target.value })} /><code>{config.branding.accentColor}</code></div></label><fieldset className="full"><legend>{t('onboarding.corner')}</legend><div className="option-pills">{(['crisp', 'soft', 'round'] as const).map((value) => <button type="button" key={value} className={config.branding.cornerStyle === value ? 'active' : ''} onClick={() => updateBranding({ cornerStyle: value })}>{t(`onboarding.${value}` as 'onboarding.crisp')}</button>)}</div></fieldset><fieldset className="full"><legend>{t('onboarding.density')}</legend><div className="option-pills">{(['comfortable', 'compact'] as const).map((value) => <button type="button" key={value} className={config.branding.density === value ? 'active' : ''} onClick={() => updateBranding({ density: value })}>{t(`onboarding.${value}` as 'onboarding.comfortable')}</button>)}</div></fieldset></div><div className="brand-preview"><span className="brand-preview-mark"><Palette size={18} /></span><span><strong>{config.branding.displayName || t('brand.platform')}</strong><small>{config.branding.siteName || t('brand.workspace')} · {localized(industryPack.name, language)}</small></span></div></div>}

        {step === 2 && <div className="wizard-step"><div className="wizard-title"><span className="step-number">03</span><div><h2>{t('onboarding.captureTitle')}</h2><p>{t('onboarding.captureBody')}</p></div></div><div className="source-choice-grid large">{sourceButton('example', ImagePlus, t('onboarding.example'), t('onboarding.exampleBody'))}{sourceButton('folder', FolderOpen, t('onboarding.folder'), t('onboarding.folderBody'))}{sourceButton('camera', Camera, t('onboarding.camera'), t('onboarding.cameraBody'))}</div>{source === 'example' ? <div className="sample-preview"><img src="/mock/blender/station-overview.png" alt={localized(industryPack.terms.sample, language)} /><div><span className="eyebrow">{t('header.synthetic')}</span><h3>{localized(industryPack.terms.sample, language, true)}</h3><p>{t('upload.syntheticBody')}</p></div></div> : <label className="source-file-picker"><span className="drop-icon">{source === 'camera' ? <Camera size={24} /> : <FolderOpen size={24} />}</span><strong>{source === 'camera' ? t('onboarding.cameraSelect') : t('onboarding.folderSelect')}</strong><small>{selectedFile?.name ?? (language === 'zh' ? '没有硬件也可以选一张示例图继续' : 'You can choose a sample without hardware')}</small><input aria-label={inputLabel} type="file" accept="image/jpeg,image/png" onChange={handleFile} /></label>}{source !== 'example' && <div className="privacy-callout"><LockKeyhole size={16} /><span><strong>{t('onboarding.local')}</strong><small>{t('onboarding.localBody')}</small><small>{t('onboarding.consentHint')}</small></span></div>}</div>}

        {step === 3 && <div className="wizard-step"><div className="wizard-title"><span className="step-number">04</span><div><h2>{t('onboarding.privacyTitle')}</h2><p>{t('onboarding.privacyBody')}</p></div></div><div className="privacy-options"><button type="button" className={`privacy-option ${config.privacy.processingMode === 'local' ? 'selected' : ''}`} onClick={() => updatePrivacy({ processingMode: 'local', uploadAuthorized: false })}><span><LockKeyhole size={19} /><strong>{t('onboarding.local')}</strong></span><small>{t('onboarding.localBody')}</small><b>{config.privacy.processingMode === 'local' ? <CheckCircle2 size={18} /> : null}</b></button><button type="button" className={`privacy-option ${config.privacy.processingMode === 'authorized-upload' ? 'selected' : ''}`} onClick={() => updatePrivacy({ processingMode: 'authorized-upload' })}><span><CloudUpload size={19} /><strong>{t('onboarding.authorized')}</strong></span><small>{t('onboarding.authorizedBody')}</small><b>{config.privacy.processingMode === 'authorized-upload' ? <CheckCircle2 size={18} /> : null}</b></button></div><div className="privacy-form"><label><span>{t('onboarding.retention')}</span><input type="number" min="1" max="3650" value={config.privacy.retentionDays} onChange={(event) => updatePrivacy({ retentionDays: Number(event.target.value) || 30 })} /></label><label className="check-row"><input type="checkbox" checked={config.privacy.deleteAfterUpload} onChange={(event) => updatePrivacy({ deleteAfterUpload: event.target.checked })} /><span>{t('onboarding.deleteAfter')}</span></label><label className="check-row"><input type="checkbox" checked={config.privacy.uploadAuthorized} onChange={(event) => updatePrivacy({ uploadAuthorized: event.target.checked, processingMode: event.target.checked ? 'authorized-upload' : 'local' })} /><span><strong>{t('onboarding.consent')}</strong><small>{t('onboarding.consentHint')}</small></span></label></div></div>}

        {step === 4 && <div className="wizard-step"><div className="wizard-title"><span className="step-number">05</span><div><h2>{t('onboarding.connectorTitle')}</h2><p>{t('onboarding.connectorBody')}</p></div></div><div className="connector-config"><div className="connector-card featured"><div className="connector-icon"><PlugZap size={20} /></div><div><span className="eyebrow">{t('onboarding.mockConnector')}</span><h3>{config.connectors.gateway}</h3><p>{t('onboarding.mockConnectorBody')}</p></div><span className="connector-status"><i />{language === 'zh' ? '模拟' : 'Simulated'}</span></div><div className="connector-selects"><label><span>MES</span><select value={config.connectors.mes} onChange={(event) => updateConnectors({ mes: event.target.value })}><option>Mock MES</option><option>Enterprise MES (adapter)</option></select></label><label><span>QMS</span><select value={config.connectors.qms} onChange={(event) => updateConnectors({ qms: event.target.value })}><option>Mock QMS</option><option>Enterprise QMS (adapter)</option></select></label><label><span>Gateway</span><select value={config.connectors.gateway} onChange={(event) => updateConnectors({ gateway: event.target.value })}><option>Simulated Gateway</option><option>Edge Gateway (adapter)</option></select></label></div><button type="button" className="primary-button" onClick={() => void testConnector()} disabled={testing}>{testing ? t('onboarding.testing') : t('onboarding.testConnection')}<PlugZap size={16} /></button>{config.connectors.testStatus === 'passed' && <div className="test-result passed"><CheckCircle2 size={17} /><span><strong>{t('onboarding.testPassed')}</strong><small>{t('header.simulation')} · {config.connectors.lastTestedAt}</small></span></div>}</div></div>}

        {step === 5 && <div className="wizard-step"><div className="wizard-title"><span className="step-number">06</span><div><h2>{t('onboarding.riskTitle')}</h2><p>{t('onboarding.riskBody')}</p></div></div><div className="risk-preview"><div className="risk-hero"><ShieldAlert size={22} /><div><strong>{t('onboarding.hardRule')}</strong><p>{t('onboarding.alwaysOn')}</p></div><span className="locked-badge"><LockKeyhole size={13} />LOCKED</span></div><div className="risk-thresholds"><label><span>{t('onboarding.reviewThreshold')}</span><input type="range" min="0.1" max="0.9" step="0.05" value={config.risk.reviewThreshold} onChange={(event) => updateRisk({ reviewThreshold: Number(event.target.value) })} /><output>{config.risk.reviewThreshold.toFixed(2)}</output></label><label><span>{t('onboarding.holdThreshold')}</span><input type="range" min="0.5" max="0.99" step="0.05" value={config.risk.holdThreshold} onChange={(event) => updateRisk({ holdThreshold: Number(event.target.value) })} /><output>{config.risk.holdThreshold.toFixed(2)}</output></label></div><div className="risk-flow"><span>0.00</span><i style={{ left: `${config.risk.reviewThreshold * 100}%` }}><b>{language === 'zh' ? '复核' : 'Review'}</b></i><i style={{ left: `${config.risk.holdThreshold * 100}%` }}><b>{language === 'zh' ? '暂扣' : 'Hold'}</b></i><span>1.00</span></div></div><div className="workspace-preview"><div><span className="preview-avatar">{config.branding.displayName.slice(0, 1) || 'V'}</span><span><strong>{config.branding.displayName || t('brand.platform')}</strong><small>{config.branding.siteName || t('brand.workspace')}</small></span></div><span>{localized(industryPack.name, language)} · {localized(industryPack.terms.item, language, true)}</span><span className="preview-privacy"><LockKeyhole size={14} />{localized(industryPack.terms.capture, language)} · {config.privacy.retentionDays}d</span></div><p className="preview-note"><ShieldCheck size={15} />{t('onboarding.previewBody')}</p></div>}

        {error && <div className="wizard-error" role="alert"><ShieldAlert size={16} />{error}</div>}
        <div className="wizard-footer"><div>{step === 0 ? <button type="button" className="text-button" onClick={resetConfig}>{language === 'zh' ? '恢复默认中性配置' : 'Reset neutral defaults'}</button> : <button type="button" className="secondary-button" onClick={() => setStep((current) => Math.max(0, current - 1))}><ArrowLeft size={15} />{t('common.previous')}</button>}</div><span>{step < steps.length - 1 ? t('onboarding.nextHint') : t('onboarding.saved')}</span>{step < steps.length - 1 ? <button type="button" className="primary-button" onClick={nextStep}>{t('common.next')}<ArrowRight size={16} /></button> : <button type="button" className="primary-button" onClick={generateWorkspace}><UploadCloud size={16} />{t('onboarding.generate')}</button>}</div>
      </section>
    </div>
  </div>
}
