import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertOctagon, ArrowLeft, ArrowRight, Check, CheckCircle2, CircleHelp, ClipboardCheck, RotateCcw, Search, ShieldAlert, Trash2, X } from 'lucide-react'
import { Link, useLocation, useRoute } from 'wouter'
import { visionQcApi } from '../api/visionQc'
import { ErrorState, LoadingState } from '../components/Feedback'
import { EvidenceViewer } from '../components/EvidenceViewer'
import { StatusBadge } from '../components/StatusBadge'
import { useI18n } from '../hooks/useI18n'
import { decisionLabel } from '../i18n'
import type { Inspection, ReviewDecision, ReviewReceipt, ReviewTask } from '../types'
import { formatAuditActor, formatDateTime, formatPolicyReason, formatScore, formatStation } from '../utils'

const decisionMeta = [
  { value: 'PASS' as const, icon: CheckCircle2, shortcut: '1' },
  { value: 'REWORK' as const, icon: RotateCcw, shortcut: '2' },
  { value: 'SCRAP' as const, icon: Trash2, shortcut: '3' },
  { value: 'INVESTIGATE' as const, icon: Search, shortcut: '4' },
  { value: 'UNABLE_TO_DECIDE' as const, icon: CircleHelp, shortcut: '5' },
]

export function ReviewWorkspacePage() {
  const [, params] = useRoute('/reviews/:taskId'); const taskId = params?.taskId ?? ''; const [, navigate] = useLocation(); const { t, language } = useI18n()
  const [task, setTask] = useState<ReviewTask | null>(null); const [inspection, setInspection] = useState<Inspection | null>(null); const [error, setError] = useState<unknown>(null); const [decision, setDecision] = useState<ReviewDecision | null>(null); const [reasonCode, setReasonCode] = useState(''); const [note, setNote] = useState(''); const [modelFeedback, setModelFeedback] = useState<'FALSE_POSITIVE' | 'POSSIBLE_MISS' | 'NONE'>('NONE'); const [confirmOpen, setConfirmOpen] = useState(false); const [impactConfirmed, setImpactConfirmed] = useState(false); const [submitting, setSubmitting] = useState(false); const [formError, setFormError] = useState<string | null>(null); const [receipt, setReceipt] = useState<ReviewReceipt | null>(null)
  const reasons = (value: ReviewDecision) => {
    const labels: Record<ReviewDecision, Array<{ value: string; zh: string; en: string }>> = {
      PASS: [{ value: 'NO_VISIBLE_NONCONFORMANCE', zh: '未发现影响质量的可见不符合', en: 'No visible quality nonconformance found' }],
      REWORK: [{ value: 'SURFACE_CONTAMINATION', zh: '表面污染，可返工清洁', en: 'Surface contamination; clean and rework' }, { value: 'LEAD_ALIGNMENT', zh: '引脚偏位，可返工校正', en: 'Lead alignment; rework correction' }],
      SCRAP: [{ value: 'STRUCTURAL_DAMAGE', zh: '结构性损伤，不可返工', en: 'Structural damage; cannot rework' }, { value: 'CRITICAL_DIMENSION', zh: '关键尺寸不符合', en: 'Critical dimension out of standard' }],
      INVESTIGATE: [{ value: 'UNKNOWN_ANOMALY', zh: '异常来源未知，需调查', en: 'Unknown source; investigate' }, { value: 'BATCH_PATTERN', zh: '同批次出现聚集模式', en: 'Pattern appears across the batch' }],
      UNABLE_TO_DECIDE: [{ value: 'INSUFFICIENT_EVIDENCE', zh: '证据不足', en: 'Insufficient evidence' }, { value: 'STANDARD_UNCLEAR', zh: '适用质量标准不明确', en: 'Applicable standard is unclear' }],
    }
    return labels[value].map((item) => ({ value: item.value, label: language === 'zh' ? item.zh : item.en }))
  }
  const load = useCallback(async () => { try { setError(null); const tasks = await visionQcApi.listReviews(); const selected = tasks.find((item) => item.id === taskId); if (!selected) throw new Error(language === 'zh' ? '未找到复核任务' : 'Review task not found'); setTask(selected); setInspection(await visionQcApi.getInspection(selected.inspectionId)) } catch (caught) { setError(caught) } }, [taskId, language])
  useEffect(() => { void load() }, [load])
  useEffect(() => { function onKeyDown(event: KeyboardEvent) { if (receipt || confirmOpen || ['INPUT', 'TEXTAREA', 'SELECT'].includes((event.target as HTMLElement).tagName)) return; const match = decisionMeta.find((item) => item.shortcut === event.key); if (match) chooseDecision(match.value) }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown) })
  const chosen = useMemo(() => decisionMeta.find((item) => item.value === decision), [decision]); const isHighRisk = decision ? ['REWORK', 'SCRAP', 'INVESTIGATE'].includes(decision) : false
  function chooseDecision(next: ReviewDecision) { setDecision(next); setReasonCode(reasons(next)[0]?.value ?? ''); setFormError(null) }
  function requestSubmit() { if (!decision) return setFormError(language === 'zh' ? '请选择一个质量结论。' : 'Choose a quality decision.'); if (!reasonCode) return setFormError(language === 'zh' ? '请选择决定理由。' : 'Choose a decision reason.'); if ((decision !== 'PASS' || isHighRisk) && note.trim().length < 8) return setFormError(language === 'zh' ? '请用至少 8 个字记录现场观察或判断依据。' : 'Write at least 8 characters describing the observation or evidence.'); if (isHighRisk) { setImpactConfirmed(false); setConfirmOpen(true) } else void submitDecision(true) }
  async function submitDecision(confirmed: boolean) { if (!decision || !task) return; setSubmitting(true); setFormError(null); try { setReceipt(await visionQcApi.submitReviewDecision(task.id, { decision, reasonCode, note, expectedVersion: task.version, modelFeedback, impactConfirmed: confirmed })); setConfirmOpen(false) } catch (caught) { setConfirmOpen(false); setError(caught) } finally { setSubmitting(false) } }
  if (error) return <div className="page"><ErrorState error={error} onRetry={load} /></div>
  if (!task || !inspection) return <div className="page"><LoadingState label={language === 'zh' ? '正在组装复核证据…' : 'Assembling review evidence…'} /></div>
  if (receipt) return <div className="page review-receipt-page"><div className="review-receipt panel"><div className="receipt-mark"><Check size={35} /></div><span className="page-kicker">{language === 'zh' ? '决定已记录 · 只追加审计' : 'Decision recorded · append-only audit'}</span><h1>{t('review.receiptTitle')}</h1><p>{t('review.receiptBody')}</p><dl><div><dt>{language === 'zh' ? '质量结论' : 'Decision'}</dt><dd>{decision ? decisionLabel(language, decision) : '—'}</dd></div><div><dt>{language === 'zh' ? '操作者' : 'Actor'}</dt><dd>{formatAuditActor(receipt.actor, language)}</dd></div><div><dt>{language === 'zh' ? '提交时间' : 'Submitted'}</dt><dd>{formatDateTime(receipt.submittedAt, true, language)}</dd></div><div><dt>{language === 'zh' ? '决策记录' : 'Decision ID'}</dt><dd><code>{receipt.decisionId}</code></dd></div><div><dt>Correlation ID</dt><dd><code>{receipt.correlationId}</code></dd></div></dl>{receipt.incidentId ? <div className="receipt-next"><ShieldAlert size={20} /><span><strong>{t('review.incidentCreated')}</strong><small>{language === 'zh' ? '批次保持受控；模拟连接器动作使用幂等键。' : 'The batch stays controlled; simulated connector actions use an idempotency key.'}</small></span></div> : <div className="receipt-next success"><CheckCircle2 size={20} /><span><strong>{t('review.approved')}</strong><small>{language === 'zh' ? '本次未创建不合格事件。' : 'No nonconformance event was created.'}</small></span></div>}<div className="receipt-actions"><button className="secondary-button" onClick={() => navigate('/reviews')}>{t('review.backQueue')}</button>{receipt.incidentId && <Link className="primary-button" href={`/incidents/${receipt.incidentId}`}>{t('review.viewIncident')}<ArrowRight size={16} /></Link>}</div></div></div>
  const selectedReason = reasons(decision ?? 'PASS').find((item) => item.value === reasonCode)?.label
  const confirmBody = language === 'zh' ? decision === 'SCRAP' ? '本次提交将创建报废审批请求；在质量主管批准前不会执行报废。' : decision === 'REWORK' ? '本次提交将保持批次受控并创建返工质量事件。' : '本次提交将保持批次暂扣并创建调查质量事件。' : t('review.confirmBody')
  return <div className="page review-workspace-page"><div className="breadcrumb"><Link href="/reviews"><ArrowLeft size={14} />{t('nav.reviews')}</Link><span>/</span><strong>{task.id}</strong></div><div className="review-workspace-heading"><div><span className="page-kicker">{t('review.kicker')}</span><div className="title-line"><h1>{t('review.title')}</h1><StatusBadge status={inspection.status} /></div><p>{inspection.context.batchNo} · {inspection.context.productCode} · {formatStation(inspection.context.station, language)}</p></div><div className="sla-card"><span>{language === 'zh' ? '建议完成时间' : 'Suggested finish'}</span><strong>{formatDateTime(task.slaAt, false, language)}</strong><small>{task.assignee ?? t('reviews.unassigned')}</small></div></div>
    <div className="review-workspace-grid"><div className="review-evidence-column"><EvidenceViewer inspection={inspection} compact /><div className="evidence-strip"><div><span>{t('inspection.score')}</span><strong>{formatScore(inspection.inference?.score)}</strong></div><div><span>{t('inspection.reviewThreshold')}</span><strong>{inspection.policy?.reviewThreshold.toFixed(2) ?? '—'}</strong></div><div><span>{t('inspection.holdThreshold')}</span><strong>{inspection.policy?.holdThreshold.toFixed(2) ?? '—'}</strong></div><div><span>Model</span><strong>{inspection.inference?.modelVersion ?? '—'}</strong></div></div><div className="review-context panel"><span><strong>{language === 'zh' ? '为什么需要人工确认：' : 'Why review is needed: '}</strong>{formatPolicyReason(inspection.policy?.reason, language)}</span><span><strong>{language === 'zh' ? '证据指纹：' : 'Evidence fingerprint: '}</strong><code>{inspection.image.sha256.slice(0, 18)}…</code></span></div></div>
      <aside className="decision-desk panel"><div className="decision-desk-head"><div><span className="eyebrow">{t('review.decisionTitle')}</span><h2>{t('review.decisionTitle')}</h2></div><ClipboardCheck size={22} /></div><p className="decision-guidance">{t('review.guidance')}</p><div className="decision-options" role="radiogroup" aria-label={language === 'zh' ? '质量结论' : 'Quality decision'}>{decisionMeta.map(({ value, icon: Icon, shortcut }) => <button key={value} role="radio" aria-checked={decision === value} className={decision === value ? `selected decision-${value.toLowerCase()}` : ''} onClick={() => chooseDecision(value)}><span className="decision-icon"><Icon size={18} /></span><span><strong>{decisionLabel(language, value)}</strong><small>{language === 'zh' ? ({ PASS: '批准当前产品继续流转', REWORK: '创建返工处置并保持批次受控', SCRAP: '提交报废审批，不会由模型自动执行', INVESTIGATE: '创建质量事件并调查未知根因', UNABLE_TO_DECIDE: '升级给质量主管，不默认放行' } as Record<string, string>)[value] : ({ PASS: 'Approve continued flow', REWORK: 'Create controlled rework disposition', SCRAP: 'Submit scrap approval; no automatic execution', INVESTIGATE: 'Create an event and investigate', UNABLE_TO_DECIDE: 'Escalate; never default to release' } as Record<string, string>)[value]}</small></span><kbd>{shortcut}</kbd></button>)}</div>{decision && <div className="decision-fields"><label><span>{t('review.reason')} <b>*</b></span><select value={reasonCode} onChange={(event) => setReasonCode(event.target.value)}>{reasons(decision).map((reason) => <option key={reason.value} value={reason.value}>{reason.label}</option>)}</select></label><label><span>{t('review.observation')} {decision !== 'PASS' && <b>*</b>}</span><textarea rows={4} placeholder={t('review.observationPlaceholder')} value={note} onChange={(event) => setNote(event.target.value)} /></label><label><span>{t('review.feedback')}</span><select value={modelFeedback} onChange={(event) => setModelFeedback(event.target.value as typeof modelFeedback)}><option value="NONE">{t('review.feedbackNone')}</option><option value="FALSE_POSITIVE">{t('review.feedbackFalsePositive')}</option><option value="POSSIBLE_MISS">{t('review.feedbackPossibleMiss')}</option></select></label></div>}{formError && <div className="inline-error" role="alert"><AlertOctagon size={15} />{formError}</div>}<div className="decision-submit"><span><ShieldAlert size={16} />{language === 'zh' ? '决定将记录操作者、时间与任务版本' : 'Actor, time, and task version are recorded'}</span><button className={`primary-button ${isHighRisk ? 'danger-button' : ''}`} onClick={requestSubmit} disabled={!decision || submitting}>{submitting ? (language === 'zh' ? '正在提交…' : 'Submitting…') : chosen ? t('review.submit', { decision: decisionLabel(language, chosen.value) }) : t('review.choose')}<ArrowRight size={16} /></button></div></aside>
    </div>
    {confirmOpen && decision && <div className="modal-backdrop" role="presentation"><section className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><button className="dialog-close" aria-label={t('common.cancel')} onClick={() => setConfirmOpen(false)}><X size={18} /></button><div className="dialog-danger-icon"><ShieldAlert size={28} /></div><span className="page-kicker">{language === 'zh' ? '高风险确认' : 'High-risk confirmation'}</span><h2 id="confirm-title">{t('review.confirmHighRisk', { decision: decisionLabel(language, decision) })}</h2><p>{confirmBody}</p><dl><div><dt>{language === 'zh' ? '影响批次' : 'Affected batch'}</dt><dd>{inspection.context.batchNo}</dd></div><div><dt>{language === 'zh' ? '检测记录' : 'Inspection'}</dt><dd>{inspection.id}</dd></div><div><dt>{t('review.reason')}</dt><dd>{selectedReason}</dd></div><div><dt>{language === 'zh' ? '当前操作者' : 'Current actor'}</dt><dd>{language === 'zh' ? '林知夏 / 质检员' : 'Demo quality operator'}</dd></div></dl><label className="impact-check"><input type="checkbox" checked={impactConfirmed} onChange={(event) => setImpactConfirmed(event.target.checked)} /><span><strong>{t('review.confirmImpact')}</strong><small>{t('review.confirmImpactBody')}</small></span></label><div className="dialog-actions"><button className="secondary-button" onClick={() => setConfirmOpen(false)}>{t('review.returnCheck')}</button><button className="primary-button danger-button" disabled={!impactConfirmed || submitting} onClick={() => void submitDecision(true)}>{submitting ? (language === 'zh' ? '写入审计链…' : 'Writing audit…') : t('review.confirm')}<ArrowRight size={16} /></button></div></section></div>}
  </div>
}
